### ISSUE TITLE
Auth config

### ISSUE THREAD

**Issue by mariuscoto** [mtanda/grafana-sumologic-datasource#1]
What kind of authentication do I need to specify in Datasource config (Basic Auth, With Credentials), in order for this to work ? It currently says “Data source is working” when saving the datasource but keeps loading when I try out a query…

**Comment by mariuscoto** [comment]
@mtanda could you help me ?

**Comment by mtanda** [comment]
Sorry, this plugin doesn't test anything, always show "Data source is working".
To use this plugin, you need to create access key and set access key as basic auth id/pass.
https://help.sumologic.com/Manage/Security/Access-Keys

And you also need to set the proxy mode in datasource config.

**Comment by mtanda** [comment]
@mariuscoto Add README for you.
https://github.com/mtanda/grafana-sumologic-datasource/blob/master/README.md

And I should inform you, this plugin doesn't work with Grafana 4.6 release.
This plugin will work with Grafana 4.7.

**Comment by mariuscoto** [comment]
I was using Grafana 4.6. Thank you for your help!
