### ISSUE TITLE
 Support for  returning multiple time series

### ISSUE THREAD

**Issue by ggarg2906sumo** [mtanda/grafana-sumologic-datasource#16]
Fields is a array of size n and map contain those n values

**Comment by ggarg2906sumo** [comment]
The fix is here https://github.com/mtanda/grafana-sumologic-datasource/pull/17
@mtanda

**Comment by mtanda** [comment]
Thanks :-)

merged your PR, https://github.com/mtanda/grafana-sumologic-datasource/pull/17
