### ISSUE TITLE
Plugin breaks with v6.4.0 or v6.4.1 - 'ace is not defined'

### ISSUE THREAD

**Issue by mattparkes** [mtanda/grafana-sumologic-datasource#25]
I updated my Grafana from `6.3.6` to `6.4.0` (and then to `6.4.1`) and now this plugin returns the following error:

```
SumoLogic plugin failed
Error: ace is not defined Evaluating https://grafana.domain.tld/public/plugins/mtanda-sumologic-datasource/module.js Loading plugins/mtanda-sumologic-datasource/module
```

I don't think I tested it on `6.4.0`, so one or both of those versions seems to break it.

**Comment by mtanda** [comment]
Recently I update the plugin, and use plugin with `6.4.x` .
Please try latest version!
