### ISSUE TITLE
Not working in Grafana 7.x

### ISSUE THREAD

**Issue by michaelfward** [mtanda/grafana-sumologic-datasource#36]
Hi,

I am seeing 202 when creating the job, and then a `DELETE` request without ever getting any data. 
<img width="696" alt="Screen Shot 2020-06-30 at 12 26 11 PM" src="https://user-images.githubusercontent.com/6685617/86168442-1022ce80-bacd-11ea-8f3f-342a62812962.png">

<img width="579" alt="Screen Shot 2020-06-30 at 12 28 19 PM" src="https://user-images.githubusercontent.com/6685617/86168559-3d6f7c80-bacd-11ea-9632-72cf7a13a5bf.png">

I'm using `grafana-server v7.0.5`

**Comment by mtanda** [comment]
Seems to work in my env.
I did test by querying `_index=sumologic_volume` .
Would you provide more information?

**Comment by michaelfward** [comment]
Hi @mtanda thanks for the quick reply!

I did more investigation. When querying, the plugin does not fetch / page the results, it immediately calls the DELETE method.

These are screenshots from an affected version:
![Screen Shot 2020-07-01 at 10 43 35 AM](https://user-images.githubusercontent.com/6685617/86275207-c4812b00-bb87-11ea-91ea-50b5a3b3b5a1.png)
![Screen Shot 2020-07-01 at 10 43 33 AM](https://user-images.githubusercontent.com/6685617/86275213-c64aee80-bb87-11ea-9442-fd0aa265908d.png)


This is correct behavior (note the `POST` to create the job, `GET` to fetch results, `DELETE` to delete):
![Screen Shot 2020-07-01 at 10 48 14 AM](https://user-images.githubusercontent.com/6685617/86275638-70c31180-bb88-11ea-83a3-ac1c52646185.png)
![Screen Shot 2020-07-01 at 10 48 00 AM](https://user-images.githubusercontent.com/6685617/86275647-73256b80-bb88-11ea-8480-8c4e71b5a381.png)
![Screen Shot 2020-07-01 at 10 47 56 AM](https://user-images.githubusercontent.com/6685617/86275650-74569880-bb88-11ea-94e7-c015fdc5ad8f.png)

**Comment by michaelfward** [comment]
I just confirmed that this issue starts in Grafana 6.7.x

**Comment by michaelfward** [comment]
I believe this is related to https://github.com/grafana/grafana/releases/tag/v6.7.0-beta1

**Comment by michaelfward** [comment]
I just confirmed the change was introduced in `6.70` release of Grafan. Pulling the first image before `6.6.2` does not have the issue.

**Comment by mtanda** [comment]
Thanks for info.
I didn't check how backendSrv change affect my plugin.
Need to investigate it. I can't promise but I'll take a time.

**Comment by michaelfward** [comment]
No problem. I haven't written Angular code in a very long time but I'm going to spend my day today trying to see if I can figure this out.

**Comment by michaelfward** [comment]
Interesting:

I did `grafana-toolkit plugin:dev` and it worked, no code change necessary.

**Comment by mtanda** [comment]
hmm, Prometheus datasource seems to call same API.
https://github.com/grafana/grafana/blob/v7.0.5/public/app/plugins/datasource/prometheus/datasource.ts#L156

I should check rxjs too.

**Comment by mtanda** [comment]
I did quick investigation, and I can't find way to call digest...

**Comment by mtanda** [comment]
@michaelfward Did you get any error message in Dev tools?

**Comment by mtanda** [comment]
I use plugin with 7.0.6. It works.
