### ISSUE TITLE
Cannot add datasource in 7.x

### ISSUE THREAD

**Issue by paul-greidanus-hs** [mtanda/grafana-sumologic-datasource#38]
I get this error when trying to add a datasource:

Unexpected token '<' Evaluating http://localhost/public/plugins/mtanda-sumologic-datasource/module.js Loading plugins/mtanda-sumologic-datasource/module
Data Source Error

This is on 7.0.4

**Comment by mtanda** [comment]
I can install plugin by following command.
```
grafana-cli --pluginUrl=https://github.com/mtanda/grafana-sumologic-datasource/releases/download/1.1.0/grafana-sumologic-datasource-1.1.0.zip plugins install grafana-sumologic-datasource;
```

**Comment by paul-greidanus-hs** [comment]
Interesting, I wonder if there is a significant difference between how I am deploying and running grafana-cli?

I am using a git clone into the plugins directory in a Jenkins pipeline to build a container which we then use.

I'll experiment with using grafana-cli in the Dockerfile instead

**Comment by paul-greidanus-hs** [comment]
Ah, I figured it out.. the checkout is typescript and the module needs to be compiled to javascript. I'm updating my scripts to use the zip file.
