### ISSUE TITLE
Not working with Grafana 5.0.0-beta1

### ISSUE THREAD

**Issue by mariuscoto** [mtanda/grafana-sumologic-datasource#6]
I get the following error when configuring the plugin:

`Cannot read property 'code' of undefined`

**Comment by mtanda** [comment]
@mariuscoto Just confirm. Did you specify `proxy` mode in datasource config page?

**Comment by mariuscoto** [comment]
I did. The datasource seems to be validated now, but when i try to create a new panel and I select the Sumologic datasource for it it starts to load something (spinning wheel) which never ends. The query inspector also seems not to be working.

**Comment by mtanda** [comment]
You may need to set `Whitelisted Cookies`. (The setting name seems to be changed in 5.x)

> To bypass Sumo Logic cookie to SumoLogic, please set "JSESSIONID,AWSELB"

https://github.com/mtanda/grafana-sumologic-datasource/blob/master/README.md

**Comment by raychaser** [comment]
FWIW things are working for me with 5.0.3 and the plugin installed using `grafana-cli` today.

**Comment by mtanda** [comment]
@raychaser Thanks for testing!!

**Comment by jordanmackie** [comment]
FWIW, I get the same error as above and I'm running 5.0.4 (commit: 7dc36ae)

```
TypeError: Cannot read property 'code' of undefined
    at eval (https://metrics.tbd.vpsvc.com/public/plugins/mtanda-sumologic-datasource/datasource.js:257:28)
    at u (https://metrics.tbd.vpsvc.com/public/build/vendor.2c3c591224fb193f7fd3.js:92:69119)
    at https://metrics.tbd.vpsvc.com/public/build/vendor.2c3c591224fb193f7fd3.js:92:69565
    at d.$digest (https://metrics.tbd.vpsvc.com/public/build/vendor.2c3c591224fb193f7fd3.js:92:75262)
    at d.$apply (https://metrics.tbd.vpsvc.com/public/build/vendor.2c3c591224fb193f7fd3.js:92:77076)
    at https://metrics.tbd.vpsvc.com/public/build/vendor.2c3c591224fb193f7fd3.js:92:73135
    at i (https://metrics.tbd.vpsvc.com/public/build/vendor.2c3c591224fb193f7fd3.js:92:21978)
    at https://metrics.tbd.vpsvc.com/public/build/vendor.2c3c591224fb193f7fd3.js:92:23440
```

**Comment by jordanmackie** [comment]
Found that the issue was that I was using the wrong API endpoint for my deployment. The current code doesn't know how to process that timeout exception, and attempts to read the .code property from a null object. Honestly its a small price to pay for this great work. Thanks!

https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security

**Comment by mtanda** [comment]
I didn't check timeout case.  I tried to fix the "'code' of undefined" error in https://github.com/mtanda/grafana-sumologic-datasource/commit/216ce1d41ff28b06c1a76c130beb794ce03c5769.
