### ISSUE TITLE
Provide option  on UI to set timeout for search jobs

### ISSUE THREAD

**Issue by navops29** [mtanda/grafana-sumologic-datasource#7]
The search job API has a hard-coded timeout of 30 seconds. This timeout seems to insufficient while running larger queries.

It would be nice to have an option on the UI to set the timeout for the search job.

**Comment by mtanda** [comment]
Thanks for feedback!
I'll add the option.

**Comment by mtanda** [comment]
I add the option in https://github.com/mtanda/grafana-sumologic-datasource/pull/8 .
